spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://**.**.**.**:3306/username?useSSL=false
    username: username
    password: ****
    # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    # redis 配置
  redis:
    port: 6379
    host: **.**.**.**
    database: 1
    password: password



server:
  address: 0.0.0.0

