spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://*.*.*.*:3306/usercenter?useSSL=false
    username: ****
    password: ******
    # session 失效时间
  session:
    timeout: 86400


server:
  address: 0.0.0.0

