spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.234.93:3306/usercenter?useSSL=false
    username: usercenter
    password: 3mDtepZZXRKXHEJj
    # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    # redis 配置
  redis:
    port: 6379
    host: 101.43.234.93
    database: 1
    password: 245680



server:
  address: 0.0.0.0

